// Package explain provides deterministic and AI-based explanations for
// CloudAttackPath instances discovered through graph traversal.
//
// Deterministic explanations are generated offline from node ID prefixes.
// AI explanations are generated by calling Anthropic or OpenAI APIs when
// the relevant environment variables are set. dp runs fully offline when
// no AI key is configured.
package explain

import (
	"fmt"
	"strings"

	"github.com/devopsproxy/dp/internal/models"
)

// ExplainAttackPath generates a deterministic, human-readable explanation
// for a CloudAttackPath by examining each node ID in the path and emitting
// a sentence that describes the security implication of that node type.
//
// The explanation is assembled from per-node sentences and joined with
// spaces. No network calls are made; the function is pure and offline.
func ExplainAttackPath(path models.CloudAttackPath) string {
	if len(path.Nodes) == 0 {
		return "No nodes in path."
	}

	var sentences []string
	for _, nodeID := range path.Nodes {
		s := sentenceForNode(nodeID)
		if s != "" {
			sentences = append(sentences, s)
		}
	}
	if len(sentences) == 0 {
		return "Attack path detected through infrastructure graph."
	}
	return strings.Join(sentences, " ")
}

// sentenceForNode returns a human-readable sentence describing the security
// implication of a graph node based on its ID prefix.
func sentenceForNode(nodeID string) string {
	switch {
	case nodeID == "Internet" || strings.HasPrefix(nodeID, "Internet_"):
		return "Traffic enters from the Internet."

	case strings.HasPrefix(nodeID, "LoadBalancer_"):
		name := stripPrefix(nodeID, "LoadBalancer_")
		return fmt.Sprintf("Service %q exposes the cluster to the Internet.", name)

	case strings.HasPrefix(nodeID, "Deployment_"):
		name := stripPrefix(nodeID, "Deployment_")
		return fmt.Sprintf("Workload %q may be compromised by an attacker.", name)

	case strings.HasPrefix(nodeID, "StatefulSet_"):
		name := stripPrefix(nodeID, "StatefulSet_")
		return fmt.Sprintf("Workload %q may be compromised by an attacker.", name)

	case strings.HasPrefix(nodeID, "DaemonSet_"):
		name := stripPrefix(nodeID, "DaemonSet_")
		return fmt.Sprintf("Workload %q may be compromised by an attacker.", name)

	case strings.HasPrefix(nodeID, "Job_"):
		name := stripPrefix(nodeID, "Job_")
		return fmt.Sprintf("Workload %q may be compromised by an attacker.", name)

	case strings.HasPrefix(nodeID, "CronJob_"):
		name := stripPrefix(nodeID, "CronJob_")
		return fmt.Sprintf("Workload %q may be compromised by an attacker.", name)

	case strings.HasPrefix(nodeID, "Pod_"):
		name := stripPrefix(nodeID, "Pod_")
		return fmt.Sprintf("Pod %q runs with insufficient isolation.", name)

	case strings.HasPrefix(nodeID, "Node_"):
		name := stripPrefix(nodeID, "Node_")
		return fmt.Sprintf("The workload runs on node %q which assumes an IAM role.", name)

	case strings.HasPrefix(nodeID, "ServiceAccount_"):
		name := stripPrefix(nodeID, "ServiceAccount_")
		return fmt.Sprintf("Service account %q has cloud permissions that could be misused.", name)

	case strings.HasPrefix(nodeID, "IAMRole_"):
		name := stripPrefix(nodeID, "IAMRole_")
		return fmt.Sprintf("IAM role %q has permissions to access cloud resources.", name)

	case strings.HasPrefix(nodeID, "S3Bucket_"):
		name := stripPrefix(nodeID, "S3Bucket_")
		return fmt.Sprintf("S3 bucket %q may contain sensitive data.", name)

	case strings.HasPrefix(nodeID, "SecretsManagerSecret_"):
		name := stripPrefix(nodeID, "SecretsManagerSecret_")
		return fmt.Sprintf("Secrets Manager secret %q may contain credentials or API keys.", name)

	case strings.HasPrefix(nodeID, "DynamoDBTable_"):
		name := stripPrefix(nodeID, "DynamoDBTable_")
		return fmt.Sprintf("DynamoDB table %q may store sensitive application data.", name)

	case strings.HasPrefix(nodeID, "KMSKey_"):
		name := stripPrefix(nodeID, "KMSKey_")
		return fmt.Sprintf("KMS key %q may be used to decrypt sensitive data.", name)

	case strings.HasPrefix(nodeID, "SSMParameter_"):
		name := stripPrefix(nodeID, "SSMParameter_")
		return fmt.Sprintf("SSM parameter %q may store secrets or configuration.", name)

	default:
		return ""
	}
}

// stripPrefix removes the given prefix from s and returns the remainder.
func stripPrefix(s, prefix string) string {
	return strings.TrimPrefix(s, prefix)
}
